### ISSUE TITLE
Change the settings data structure to be more flexible

### ISSUE THREAD

**Issue by llevera** [AffinityID/PowerUp#13]
Currently the settings "contract" is a hash of either arrays or strings.

Having this as a hash of hashes or arrays or strings will allow the use of more flexible settings formats (for eg, YAML)

**Comment by ashmind** [comment]
Looking at settings, I don't think there anything limiting the contract other than the way we read them -- which is defined by the settings format. So I'll close this and update the data structure if we do a format change in the future.
