### ISSUE TITLE
Introduce diagnostics 

### ISSUE THREAD

**Issue by llevera** [AffinityID/PowerUp#19]
We need something within the modules that will diagnose whether everything required is in place to run the commandlets.

Examples:
PowerUpWeb: make sure the IIS snapin exists
PowerUpRemote: check permissions etc

**Comment by ashmind** [comment]
I don't think it is possible to solve this in a useful way -- some basic checks can be done, but it wouldn't save much effort as there are too many ways things can go wrong. E.g. for PowerUpRemote it is permissions, firewalls, missing shares, double hop issues, etc, etc.
